import React, { Component } from 'react';
import './App.css';
import ReactMapGL from 'react-map-gl';
import { ListGroup, ListGroupItem } from 'reactstrap';
import { Container, Row, Col} from 'reactstrap';
import { Media } from 'reactstrap';
import SearchBar from './search_bar';

import { Nav, NavItem, NavLink } from 'reactstrap';
import { Dropdown, DropdownToggle, DropdownMenu, DropdownItem } from 'reactstrap';





class App extends Component {


  
  constructor(props) {
    super(props);
    this.toggle = this.toggle.bind(this);
    this.select = this.select.bind(this);

    this.state = {
      dropdownOpen: false,
      value : "---Select---"
    };

  }

  toggle() {
    this.setState(prevState => ({
      dropdownOpen: !prevState.dropdownOpen
    }));
  }
  select(event) {
    this.setState({
      dropdownOpen: !this.state.dropdownOpen,
      value: event.target.innerText
    });
  }
  handleSubmit(event) {
    event.preventDefault();
  }
  handleClick(value,defvalue){
    alert('You have chosen ' + defvalue + ' peices ' + 'in size ' + value);
  }






  render() {
    return (



      <div>
      <Row>
      <Col xs="12" md="6" className = "imgcontain">
        <img className="imgstyle" src="https://source.unsplash.com/collection/190727/" alt="unsplash"/>
        <img className="imgstyle" src="https://source.unsplash.com/1600x900/?nature,water" alt="unsplash"/>
        <img className="imgstyle" src="https://source.unsplash.com/user/erondu/1600x900" alt="unsplash"/>
        </Col>

      <Col className="imgstyle" xs="6" md="3" >
      <div className = "fixing">
      <p className="App-header"> <h1> Images from Unsplash </h1>
      These are some random images that were generated by unsplash. They are some beautiful photos...
      <p> The various sizes of the photos are available </p>
      <hr/>
      <p> Choose Size </p>
      <Dropdown isOpen={this.state.dropdownOpen} toggle={this.toggle}>
        <DropdownToggle caret> {this.state.value}


        </DropdownToggle>
        <DropdownMenu >

          <DropdownItem onClick={this.select}>Xtra Small</DropdownItem>
          <DropdownItem onClick={this.select}>Small</DropdownItem>
          <DropdownItem onClick={this.select} >Large</DropdownItem>
          <DropdownItem onClick={this.select} >Xtra Large</DropdownItem>

        </DropdownMenu>
      </Dropdown>
    <br/>


    <div>
    <p>Choose quantity</p>
    <select defaultValue={this.state.selectValue} onChange={this.handleChange} className = "dropdownstyle" ref="choice">

    <option value="1">1</option>
    <option value="2">2</option>
    <option value="3">3</option>
    <option value="4">4</option>
    <option value="5">5</option>
    <option value="6">6</option>
    <option value="7">7</option>
    <option value="8">8</option>
    <option value="9">9</option>
    <option value="10">10</option>


  </select>

  </div>


      <hr/>
      <form onSubmit={this.handleSubmit}>
        <button type="submit" className ="buttonstyle" onClick={()=>this.handleClick(this.state.value,this.refs.choice.value)}>Submit</button>

      </form>
      <hr />
      <div>
       <Nav vertical>
         <NavItem>
           <NavLink href="#">Color and composition</NavLink>
         </NavItem>
         <NavItem>
           <NavLink href="#">Color and hue</NavLink>
         </NavItem>
         <NavItem>
           <NavLink href="#">Share</NavLink>
         </NavItem>
      </Nav>
      <hr />

     </div>
      </p>
      </div>

      </Col>



      </Row>

      <div>
      <p > <h3 className ="App"> Related Images </h3>
           </p>
           <div className = "horizontalimage">
           <Row>
           <Col xs="12" md="6">
           <img className="imgstyle" src="https://source.unsplash.com/collection/190727/" alt="unsplash"/></Col>
           <Col>
           <img className="imgstyle" src="https://source.unsplash.com/1600x900/?nature,water" alt="unsplash"/></Col>
           <Col xs="12" md="6">
           <img className="imgstyle" src="https://source.unsplash.com/user/erondu/1600x900" alt="unsplash"/>
           </Col>
           <Col xs="12" md="6" >
           <img className="imgstyle" src="https://source.unsplash.com/user/erondu/1600x900" alt="unsplash"/>
           </Col>
           </Row>
            </div>
      </div>
      </div>






    );
  }
}

export default App;
